set(_AMENT_PACKAGE_NAME "ros2_qrcodereader")
set(ros2_qrcodereader_VERSION "0.0.0")
set(ros2_qrcodereader_MAINTAINER "pix <55618696+ChaelPix@users.noreply.github.com>")
set(ros2_qrcodereader_BUILD_DEPENDS "rclcpp" "sensor_msgs" "cv_bridge" "OpenCV")
set(ros2_qrcodereader_BUILDTOOL_DEPENDS "ament_cmake")
set(ros2_qrcodereader_BUILD_EXPORT_DEPENDS "rclcpp" "sensor_msgs" "cv_bridge" "OpenCV")
set(ros2_qrcodereader_BUILDTOOL_EXPORT_DEPENDS )
set(ros2_qrcodereader_EXEC_DEPENDS "ZBar" "rclcpp" "sensor_msgs" "cv_bridge" "OpenCV")
set(ros2_qrcodereader_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(ros2_qrcodereader_GROUP_DEPENDS )
set(ros2_qrcodereader_MEMBER_OF_GROUPS )
set(ros2_qrcodereader_DEPRECATED "")
set(ros2_qrcodereader_EXPORT_TAGS)
list(APPEND ros2_qrcodereader_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
